-- 创建用户表
CREATE TABLE IF NOT EXISTS `user`(
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(50) NOT NULL,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建头像信息表
CREATE TABLE IF NOT EXISTS `avatar`(
  id INT PRIMARY KEY AUTO_INCREMENT, 
  filename VARCHAR(255) NOT NULL UNIQUE,
  mimetype VARCHAR(30),
  size INT,
  user_id INT,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- user表增加avatar_url（头像图片url）字段
ALTER TABLE user ADD avatar_url VARCHAR(200);